FROM tiangolo/uvicorn-gunicorn:python3.11-slim

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install python dependencies
COPY requirements/requirements.txt .
RUN pip install -r requirements.txt

# add app
COPY . .
