version: "3.8"

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://derek:password@db:5432/db
    ports:
      - 8008:8000
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=derek
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
