name: push to master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      HEROKU_APP_NAME: infinite-shore-17009
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/summarizer
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Packages
        run: echo "$GITHUB_TOKEN" | docker login -u "$GITHUB_ACTOR" --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Pull images
        run: |
          docker pull "${{ env.IMAGE }}-builder:latest" || true
          docker pull "${{ env.IMAGE }}-final:latest" || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from "${{ env.IMAGE }}-builder:latest" \
            --tag "${{ env.IMAGE }}-builder:latest" \
            --file ./src/Dockerfile.prod \
            ./src
          docker build \
            --cache-from "${{ env.IMAGE }}-final:latest" \
            --tag "${{ env.IMAGE }}:latest" \
            --tag "${{ env.HEROKU_REGISTRY_IMAGE }}:latest" \
            --file ./src/Dockerfile.prod \
            ./src
      - name: Log in to the Heroku Container Registry
        run: docker login -u _ -p "$HEROKU_AUTH_TOKEN" registry.heroku.com
        env:
          HEROKU_AUTH_TOKEN: "${{ secrets.HEROKU_AUTH_TOKEN }}"
      - name: Push to the registry
        run: docker push ${{ env.HEROKU_REGISTRY_IMAGE }}:latest
      - name: Set environment variables
        run: |
          echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> "$GITHUB_ENV"
          echo "HEROKU_AUTH_TOKEN=${{ secrets.HEROKU_AUTH_TOKEN }}" >> "$GITHUB_ENV"
      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex
          root: .bumpversion.cfg
          regex_pattern: 'current_version = (?<version>\d+\.\d+\.\d+)'
